apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-app-c2
  labels:
    app: nfs-app-c2
    kubernetes.io/instance: nfs-app-c2
    kubernetes.io/name: nfs-app-c2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-app-c2
  template:
    metadata:
      labels:
        app: nfs-app-c2
        kubernetes.io/instance: nfs-app-c2
        kubernetes.io/name: nfs-app-c2
    spec:
      containers:
        - name: debian
          image: lalitjavale/ioapps:centos8-fio
          command: ["sh"]
          args: [ "/run_io" ]
          volumeMounts:
            - mountPath: /mnt/v1
              name: v1
      volumes:
        - name: v1
          persistentVolumeClaim:
            claimName: nfs-shared-20
