apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-shared-2
  labels:
    robin.io/nfs-server-type: "exclusive"
    robin.io/replication: "2"
    robin.io/faultdomain: "disk"
spec:
  storageClassName: robin
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
