apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-shared-31
  labels:
    robin.io/rwx_force_single_replica : "1"
spec:
  storageClassName: robin
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
